[package]
name = "routerify"
version = "0.1.2"
description = "A lightweight router implementation with middleware support for the rust HTTP library hyper"
homepage = "https://github.com/routerify/routerify"
repository = "https://github.com/routerify/routerify"
keywords = ["hyper", "http", "routing", "middleware"]
categories = ["asynchronous", "web-programming", "web-programming::http-server"]
authors = ["Rousan Ali <rousanali786@gmail.com>"]
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
hyper = "0.13"
http = "0.2"
regex = "1.3"
lazy_static = "1.4.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }