[package]
name = "routerify"
version = "1.1.1"
description = "A lightweight and modular router implementation with middleware support for the Rust HTTP library hyper.rs."
homepage = "https://github.com/routerify/routerify"
repository = "https://github.com/routerify/routerify"
keywords = ["hyper", "hyper-rs", "router", "routing", "middleware"]
categories = ["asynchronous", "web-programming", "web-programming::http-server"]
authors = ["Rousan Ali <hello@rousan.io>"]
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
hyper = "0.13"
http = "0.2"
regex = "1.3"
lazy_static = "1.4"
percent-encoding = "2.1"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
stream-body = "0.1"